config/routes.rb
Rails.application.routes.draw do
  # get 'book_ads/new'
  # get 'books/new'
  root 'homepage#welcome_screen'

  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'sign_up', to: 'users#new'

  get 'confirm_email', to: 'users#confirm_email'
  get 'confirmation_page', to: 'users#confirmation_page'
  # get 'welcome_screen', to: 'homepage#welcome_screen'
  get 'user_dashboard', to: 'dashboard#user_dashboard'
  
  get 'message_window_new', to: 'dashboard#message_window_new'
  # post 'advanced_search_link', to: 'dashboard#advanced_search_link'
  post 'advanced_search_results', to: 'dashboard#advanced_search_results'
  get 'advanced_search_results', to: 'dashboard#advanced_search_results'
  get 'unread_message_count', to: 'dashboard#unread_message_count'
  # get 'edit_profile', to: 'dashboard#edit_profile_page'
  # post 'update_profile', to: 'dashboard#update_profile'

  get 'mark_it_read_host', to: 'messages#mark_it_read_host'
  get 'mark_it_read_user', to: 'messages#mark_it_read_user'

  get 'welcome_screen', to: 'homepage#welcome_screen'

  get 'message_window', to: 'messages#message_window'
  get 'user_book_chat', to: 'messages#user_book_chat'
  get 'host_book_chat', to: 'messages#host_book_chat'

  post 'host_book_send_message', to: 'messages#host_book_send_message'
  post 'user_book_send_message', to: 'messages#user_book_send_message'

  get 'mark_as_important', to: 'messages#mark_as_important'
  get 'unmark_as_important', to: 'messages#unmark_as_important'

  # get 'dynamic_messages', to: 'messages#dynamic_messages'
  # post 'dynamic_messages', to: 'messages#dynamic_messages'

  get 'forget_password_form', to: 'password_resets#new'

  # get 'password_reset_form', to: 'password_resets#edit'

  # post 'update_password', to: 'password_resets#update'

  get 'edit_profile', to: 'dashboard#edit_profile_page'
  post 'update_profile', to: 'dashboard#update_profile'

  get 'new_book', to: 'book#new'
  get 'book_detail_page', to: 'book#book_details'
  get 'see_all_books', to: 'book#see_all_books'
  get 'request_book_details', to: 'book#request_book_details'
  post 'send_request_book_message', to: 'book#send_request_book_message'
  get 'see_all_external_books', to: 'book#see_all_external_books'
  get 'delete_book', to: 'book#delete_book'

  post 'add_book', to: 'book#add_book'
  get 'edit_book', to: 'book#edit_book_page'
  post 'update_book', to: 'book#update_book'
  get 'review', to: 'book#review'

  # get 'new_book_ad', to: 'book_ads#new'
  # post 'add_book_ad', to: 'book_ads#add_book_ad'

  post 'submit_feedback', to: 'feedback#submit_feedback'
  post 'submit_category', to: 'category#submit_category'

  resources :sessions, only: [:create]
  resources :users
  resources :password_resets
  resources :dashboard
  resources :password_resets
  resources :books
  # resources :books do
  #   collection do 
  #     get :autocomplete
  #   end
  # end
  # resources :book_ads
  resources :feedback
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	layout "user_dashboard_layout"


	def user_dashboard
		@user = User.find(session[:user_id])

		@my_books = Book.active.where(user_id: session[:user_id])
		# @book_ads = bookAd.where(user_id: session[:user_id])
		if @user.check_profile_complete_status(session[:user_id])
			@external_books = Book.where.not(user_id: session[:user_id]).active.available
		else
			@external_books = []
    end
	end

	def edit_profile_page
		@user = User.find(session[:user_id])
	end

	def update_profile
		@user = User.find(session[:user_id])
		if @user.update_attributes(user_params)
			flash[:success] = "The profile was updated successfully."
			redirect_to edit_profile_path
  	else
  		flash[:error] = "Error while updating Profile.."
  		redirect_to edit_profile_path
  	end	
	end


	def advanced_search_results
		# byebug
		@user = User.find(session[:user_id])
		if @user.check_profile_complete_status(session[:user_id])
			book_id_params =  Book.advance_search(session[:user_id],params[:book_name],params[:category],params[:city],params[:top_search_button],params[:bottom_search_button])
			# book_id_string = book_id_params.tr("/", ",")
			# book_id_array = book_id_string.split(",")
			# byebug
			@book = Book.where(id: book_id_params)
			@books = Book.where(id: book_id_params).paginate(:page => params[:page], :per_page => 10)
		else
			flash[:error] = "You are not authorised to Search Book since your profile is Incomplete,So complete it fast."
      redirect_to edit_profile_path
    end
	end

	def user_params
		params.require(:user).permit(User.attribute_names + [:profile_pic])
	end
	
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/advanced_search_results.html.erb
<div class="container">
  <div class="row mb-2">
  	<% if @books.count > 0 %>
	  	<% if params[:book_name].blank? && params[:category].blank? && params[:city].blank? %>
	  		<h3 class="pseudo_border" style="padding-left: 11px;">Search Results for all Books</h3>
	  	<%else%>
	  		<h3 class="pseudo_border" style="padding-left: 11px;">Search Results for</h3><h6 style="line-height: 46px;"><%= '('  'Book Name:' + params[:book_name] + ',' + "Category:" + params[:category] + ',' + 'City:' + params[:city] + ')' %></h6>
	  	<%end%>
  	<%end%>
  	<%  @books.each do |book| %>
	    <div class="col-md-12">
	      <div class="card flex-md-row mb-4 box-shadow h-md-250 index-page-cards">
	      	<a href="<%= request_book_details_path(book) %>" style="text-decoration: none;">
          <img class="img-fluid img-thumbnail" style="height: 240px;width: 180px;margin: 15px;" src="<%= book.get_default_image_for_index_page%>" alt=""></a>
	        <div class="card-body d-flex flex-column align-items-start">
	          <h4 class="mb-0">
	          	<%= truncate(book.book_name, length: 30) %>
	          </h4>
	          <!-- <div class="mb-1 text-muted"><= book.user.first_name %> <%= book.user.last_name %></div> -->
	          <p>Category:<%= book.category.try(:name) %></p>
	          <p>Location:<%= book.location_formating %></p>
	          <p><%= truncate(book.description, length: 105) %></p>
	          <p class="mb-1 text-muted">by <a><%= book.user.name %></a>, <%= book.created_at %></p>
	          <p display-label><i class="fas fa-rupee-sign"></i> <%= book.price %></p>
	          <a href="<%= request_book_details_path(book) %>" class="btn btn-success view-details-btn"><i class="fas fa-eye"></i> View Details</a>
	        </div>
	      </div>
	      <!-- <hr> -->
	    </div>
    <%end%>
  </div>
  <% if @books.count == 0 %>
	  <div id="no-result-found">
			<h1>Sorry No Result Found :/</h1>
		</div>
	<%end%>
</div><br>
<div class="digg_pagination" style="float:right;">
	<%= will_paginate @books %>
</div>
<br><br>

app/views/dashboard/edit_profile_page.html.erb
<br>
<div class="container">
	<%if flash[:error]%>
		<div class="error_messages alert alert-danger"><%= flash[:error] %></div>
	<% end %>
	<%if flash[:success]%>
		<div class="error_messages alert alert-success"><%= flash[:success] %></div>
	<% end %>
    <div class="span3 new-profile-well">
        <center>
	        <a href="#aboutModal" data-toggle="modal" data-target="#myModal"><%= image_tag @user.profile_pic.present? ? @user.profile_pic.url(:thumb) : "default-profile-image.png",class: 'avatar img-circle profile-front-page-image' %><%= @user.edit_profile_complete_status_front(session[:user_id]).html_safe %></i></a>
	        <h3 style="padding-top: 10px;font-size: 24px;"><%= @user.name %></h3>
	        <em>Click on Profile pic for more detail</em>
		</center>
    </div>
	<!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	    <div class="modal-dialog">
	        <div class="modal-content edit-profile-modal-content">
	            <!-- Modal Header -->
	            <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title" id="myModalLabel" style="font-size: 18px;padding-right: 247px;">More About <%= @user.first_name %></h4>
                </div>
	            
	            <!-- Modal Body -->
	            <div class="modal-body">
	            	<%= form_for @user, :url => update_profile_path, method: "post", html:{role: 'form', multipart: 'true',id: 'edit_profile_form'}  do |f| %>
		            	<center>
                  	<%= image_tag @user.profile_pic.present? ? @user.profile_pic.url(:thumb) : "default-profile-image.png",class: 'avatar img-circle', height: '140',width:'140' %><%= @user.edit_profile_complete_status_modal(session[:user_id]).html_safe %></i><br>
                  	 <%= f.file_field :profile_pic,style: 'position:absolute;left: 268px;top: 161px;' %>
                  	 <h3 style="padding-top: 10px;font-size: 24px;" class=""><%= @user.name %>,<small style="font-size: 65%;"><%= @user.user_location_formating %></small></h3>
                  	<input type="file" id="image_upload_dialog" name="user[profile_pic]" style="display: none;" accept="image/x-png,image/gif,image/jpeg" />
               		</center>
               		<% if !@user.check_profile_complete_status(session[:user_id]) %>
	            			<center>
	            				<font color="#F8304D">Profile is incomplete,please complete it fast by filling all manadatory fields.</font>
	            			</center>
	            		<%else%>
	            		<%end%>
	               		<hr>
                		<div class="form-row">
									    <div class="form-group col-md-6">
									      	<label>First Name</label><font color="#F8304D">*</font>
									      	<%= f.text_field :first_name, {class: 'form-control'}  %>
									    </div>
									    <div class="form-group col-md-6">
									      	<label>Last Name</label><font color="#F8304D">*</font>
									      	<%= f.text_field :last_name, {class: 'form-control'}  %>
									    </div>
										</div>

										<div class="form-row">
									    <div class="form-group col-md-4">
									      	<label>Country</label><font color="#F8304D">*</font>
									      	<%= f.text_field :country_field, {class: 'form-control'}  %>
									    </div>
									    <div class="form-group col-md-4">
									      	<label>State</label><font color="#F8304D">*</font>
									      	<%= f.text_field :state, {class: 'form-control'}  %>
									    </div>
									    <div class="form-group col-md-4">
									      	<label>City</label><font color="#F8304D">*</font>
									      	<%= f.text_field :city, {class: 'form-control'}  %>
									    </div>
										</div>

										<div class="form-group">
								    		<label>About Yourself</label><font color="#F8304D">*</font>
								      	<%= f.text_area :about_yourself, {class: 'form-control',:placeholder => "Describe in detail more about yourself and the book you provide."}  %>
								  	</div>

										<div class="form-row">
									    <div class="form-group col-md-6">
								      	<%= f.label :pincode, 'Pincode'  %>
								      	<%= f.text_field :pincode, {class: 'form-control'}  %>
									    </div>
									    <div class="form-group col-md-6">
								      	<%= f.label :email, 'Email'  %>
							      		<%= f.text_field :email, {class: 'form-control',disabled: true}  %>
								    	</div>
										</div>

								  	<div class="form-group">
								    	<%= f.label :address, 'Address'  %>
								      	<%= f.text_area :address, {class: 'form-control'}  %>
								  	</div>
							    <div class="form-row">
								    <div class="form-group col-md-12">
								     	<%= f.label :phoneno, 'Phone No' %>
							      		<%= f.text_field :phoneno, {class: 'form-control'}  %>
								    </div>
								    
							    </div>
					  
	            	</div>
	            
		            <!-- Modal Footer -->
		            <div class="modal-footer" style="padding-right: 294px;">
		            	<center>
                  		<input class="btn btn-default" name="commit" type="submit" value="Update Profile">
                  	</center>
	            	</div>
            <%end%>  
	        </div>
	    </div>
	</div>
</div><br><br><br>

app/views/dashboard/message_window.html.erb
  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-5">

<!--         <h1 class="my-4">Page Heading
          <small>Secondary Text</small>
        </h1> -->

       <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Inbox</h5>
            <div class="card-body message-inbox" style="padding: 0px !important;">
              <ul style="max-width: 397px !important;list-style-type: none;margin: 0;padding-left:0;">
              	<% @HostBookMessages.each do |host_book_message| %>
								  <li >
								  	<a target="" href="<%=host_book_chat_path(host_book_message.book_request_id)%>" class="message-inbox-link host-book-inbox-link">
									  	<div class="row message-inbox-image">
									  		<div class="col-md-2">
									    		<%= image_tag "images",class: ' rounded-circle profile-pic-thumbnail',style: 'margin-left:19px;' %>
									    	</div>
									    	<div class="col-md-10">
									    		<p>Message:<%=host_book_message.message_description%></p>
									    		<p>Sender:Host</p>
									    	</div>
						    			</div>
						    		</a>
					    		</li><hr class="inbox">
					    	<%end%>
					    	<% @UserBookMessages.each do |user_book_message| %>
								  <li >
								  	<a target="" href="<%=user_book_chat_path(user_book_message.book_request_id)%>" class="message-inbox-link user-book-inbox-link">
									  	<div class="row message-inbox-image">
									  		<div class="col-md-2">
									    		<%= image_tag "images",class: ' rounded-circle profile-pic-thumbnail',style: 'margin-left:19px;' %>
									    	</div>
									    	<div class="col-md-10">
									    		<p>Message:<%=user_book_message.message_description%></p>
									    		<p>Sender:User</p>
									    	</div>
						    			</div>
						    		</a>
					    		</li><hr class="inbox">
					    	<%end%>
							</ul>
            </div>
          </div>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-7" id="#section7">

        <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Messages</h5>
            <div class="card-body message-box">
            	<div class="msg-box">
				        <img class="msg-box-loader" style="display:none;" src="https://www.drupal.org/files/loading.gif "/>
<!-- 	              <div class="talk-bubble tri-right left-top" style="background-color:#f0f0f0;">
								  <div class="talktext">
								    <p>This one adds a right triangle on the left, flush at the top by using .tri-right and .left-top to specify the location.</p>
								  </div>
								</div>
								<div class="talk-bubble tri-left right-top" style="float:right;background-color:#F1F8FA;">
								  <div class="talktext">
								    <p>This one adds a right triangle on the left, flush at the top by using .tri-right and .left-top to specify the location.</p>
								  </div>
								</div>
								<div class="talk-bubble tri-right left-top" style="background-color:#f0f0f0;">
								  <div class="talktext">
								    <p>This one adds a right triangle on the left, flush at the top by using .tri-right and .left-top to specify the location.</p>
								  </div>
								</div>
								<div class="talk-bubble tri-left right-top" style="float:right;background-color:#F1F8FA;">
								  <div class="talktext">
								    <p>This one adds a right triangle on the left, flush at the top by using .tri-right and .left-top to specify the location.</p>
								  </div>
								</div>
								<div class="talk-bubble tri-left right-top" style="float:right;background-color:#F1F8FA;">
								  <div class="talktext">
								    <p>This one adds a right triangle on the left, flush at the top by using .tri-right and .left-top to specify the location.</p>
								  </div>
								</div> -->
							</div>
            </div>
            <div class="card-footer">
				      <div class="form-group">
	    					<%= text_area_tag :message,"", class: 'form-control', placeholder: 'Type your message...'  %>
	  					</div>
	  					<div class="form-group">
	    					<input class="btn btn-default" name="commit" type="submit" value="Send">
	  					</div>
				    </div>
          </div>

      </div>

    </div>
    <!-- /.row -->


  </div>
  <!-- /.container -->

app/views/dashboard/message_window_new.html.erb
    
    <div class="container">

	    <div class="row">
	     <!-- Sidebar Widgets Column -->
	      <div class="col-md-7 id="#section7">

	        <!-- Search Widget -->
	          <div class="card my-4">
	            <h5 class="card-header">Messages</h5>
	            <div class="card-body message-box">
	              <div class="talk-bubble tri-right left-top" style="background-color:#f0f0f0;">
								  <div class="talktext">
								    <p>This one adds a right triangle on the left, flush at the top by using .tri-right and .left-top to specify the location.</p>
								  </div>
								</div>
								<div class="talk-bubble tri-left right-top" style="float:right;background-color:#F1F8FA;">
								  <div class="talktext">
								    <p>This one adds a right triangle on the left, flush at the top by using .tri-right and .left-top to specify the location.</p>
								  </div>
								</div>
								<div class="talk-bubble tri-right left-top" style="background-color:#f0f0f0;">
								  <div class="talktext">
								    <p>This one adds a right triangle on the left, flush at the top by using .tri-right and .left-top to specify the location.</p>
								  </div>
								</div>
								<div class="talk-bubble tri-left right-top" style="float:right;background-color:#F1F8FA;">
								  <div class="talktext">
								    <p>This one adds a right triangle on the left, flush at the top by using .tri-right and .left-top to specify the location.</p>
								  </div>
								</div>
								<div class="talk-bubble tri-left right-top" style="float:right;background-color:#F1F8FA;">
								  <div class="talktext">
								    <p>This one adds a right triangle on the left, flush at the top by using .tri-right and .left-top to specify the location.</p>
								  </div>
								</div>
	            </div>
	            <div class="card-footer">
					      <div class="form-group">
		    					<%= text_area_tag :message,"", class: 'form-control', placeholder: 'Type your message...'  %>
		  					</div>
		  					<div class="form-group">
		    					<input class="btn btn-default" name="commit" type="submit" value="Send">
		  					</div>
					    </div>
	          </div>

	      </div>

	    </div>

	  </div>

app/views/dashboard/user_dashboard.html.erb
  <div class="container">
	<% if session[:user_id].present? %>

      <%if flash[:error]%>
        <div class="error_messages alert alert-danger"><%= flash[:error] %></div>
      <% end %>
      <%if flash[:success]%>
        <div class="error_messages alert alert-success"><%= flash[:success] %></div>
      <% end %>

		  <% content_for :head do %>
			  <meta name="turbolinks-cache-control" content="no-cache">
			<% end %>

			<div class="row">
				<div class="col-md-11">
					<% if @my_books.count > 0 %>
						<h3 class="pseudo_border" style="padding-left: 11px;">My Books</h3>
					<%end%>
				</div>
				<div class="col-md-1">
					<% if @my_books.count >= 4 %>
						<a class="link-color" href="<%= see_all_books_path %>"><h4 style="font-size: 19px;line-height:57px;">See All</h4></a>
					<%end%>
				</div>
			</div>
			<% if @my_books.count <= 4 %>
				<div class="my_books_scroller" data-slick='{"slidesToShow": <%=  @my_books.count %>}'>
			<%else%>
				<div class="my_books_scroller">
			<%end%>
				<% @my_books.each do |my_book| %>
					<div class="col-md-3 mb-3">
						<a href="<%= book_detail_page_path(my_book) %>" style="text-decoration: none;" class="link-color">

							<div class="flip-card">
							  <div class="flip-card-inner">
							    <div class="flip-card-front">
							      <%= image_tag my_book.get_default_image_for_index_page,class: '', height: '320' ,width: '240' %>
							    </div>
							    <div class="flip-card-back">
							      <h3 title="<%= my_book.book_name %>"><%= truncate(my_book.book_name, length:13) %><br><%= "(" << my_book.category.try(:name) << ")"  %></h3> 
							      <p><%= my_book.user.name %></p> 
							      <p><%=  my_book.location_formating %></p>
							      <p><%=  my_book.availability_status %></p>
							      <div class="card-footer" style="top: 45px;position: relative;">
								    	<div class="row">
								    		<div class="col-md-4">
										    	<%= link_to edit_book_path(my_book) do %>
													  <i title="Edit" class="far fa-edit" style="color: #212529;"></i>
													<% end %>
												</div>
												<div class="col-md-3">
													<% if my_book.book_requested_before == false %>
														<a title="Delete" href="<%=delete_book_path(my_book)%>" onclick="return confirm('Are you sure you want to delete this book?');"><i class="fa far fa-trash-alt" aria-hidden="true" style="color: #212529;"></i></a>	  
													<%end%>
												</div>
												<div class="col-md-5">
								      		<span style="color: #212529;margin-right: 2px;"><i class="fas fa-rupee-sign"></i> <%= my_book.price %></span>
								      	</div>
							      	</div>
						    		</div>
							  	</div> 
					    	</div>
							</div>

						</a>
					</div>
				<%end%>
			</div>
		</div><br>

		

		<div class="container">
			<div class="row">
				<div class="col-md-11">
					<% if @external_books.count > 0 %>
						<h3 class="pseudo_border" style="padding-left: 11px;">Recently Uploaded Books</h3>
					<%end%>
				</div>
				<div class="col-md-1">
					<% if @external_books.count >= 4 %>
						<a class="link-color" href="<%= see_all_external_books_path %>" style="line-height: 50px;"><h4 style="font-size: 19px;line-height:57px;">See All</h4></a>
					<%end%>
				</div>
			</div>
<!-- 			<button style="" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect">
			  <i class="fas fa-chevron-left"></i>
			</button> -->
			<% if @external_books.count <= 4 %>
				<div class="ext_books_scroller" data-slick='{"slidesToShow": <%=  @external_books.count %>}'>
			<%else%>
				<div class="ext_books_scroller">
			<%end%>
				<% @external_books.each do |external_book| %>
					<div class="col-md-3 mb-3">
						<a href="<%= request_book_details_path(external_book) %>" style="text-decoration: none;" class="link-color">

							<div class="flip-card">
							  <div class="flip-card-inner">
							    <div class="flip-card-front">
							      <%= image_tag external_book.get_default_image_for_index_page,class: '', height: '320' ,width: '240' %>
							    </div>
							    <div class="flip-card-back">
							      <h3 title="<%= external_book.book_name %>"><%= truncate(external_book.book_name, length:13) %><br><%= "(" << external_book.category.try(:name) << ")"  %></h3>
							      <p><%= external_book.user.name %></p> 
							      <p><%=  external_book.location_formating %></p>
							      <div class="card-footer" style="top: 74px;position: relative;">
								    	<div class="row">
								    		<div class="col-md-4">
										    	<%= link_to "" do %>
													  <i class="far fa-heart" style="color: #212529;"></i>
													<% end %>
												</div>
												<div class="col-md-3">
													
												</div>
												<div class="col-md-5">
								      		<span style="color: #212529;margin-right: 2px;"><i class="fas fa-rupee-sign"></i> <%= external_book.price %></span>
								      	</div>
						      		</div>
						    		</div>
							  	</div> 
					    	</div>
							</div>

						</a>
					</div>
				<%end%>
			</div>
		</div>
	</div>

	</div>

		<% if @my_books.count > 4 %>
			<button style="" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mybooks-left">
			  <i class="fas fa-chevron-left"></i>
			</button>
			<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mybooks-right">
			  <i class="fas fa-chevron-right"></i>
			</button>
		<%end%>

	<%end%>

	<br><br><br>