config/routes.rb
Rails.application.routes.draw do
  # get 'book_ads/new'
  # get 'books/new'
  root 'homepage#welcome_screen'

  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'sign_up', to: 'users#new'

  get 'confirm_email', to: 'users#confirm_email'
  get 'confirmation_page', to: 'users#confirmation_page'
  # get 'welcome_screen', to: 'homepage#welcome_screen'
  get 'user_dashboard', to: 'dashboard#user_dashboard'
  
  get 'message_window_new', to: 'dashboard#message_window_new'
  # post 'advanced_search_link', to: 'dashboard#advanced_search_link'
  post 'advanced_search_results', to: 'dashboard#advanced_search_results'
  get 'advanced_search_results', to: 'dashboard#advanced_search_results'
  get 'unread_message_count', to: 'dashboard#unread_message_count'
  # get 'edit_profile', to: 'dashboard#edit_profile_page'
  # post 'update_profile', to: 'dashboard#update_profile'

  get 'mark_it_read_host', to: 'messages#mark_it_read_host'
  get 'mark_it_read_user', to: 'messages#mark_it_read_user'

  get 'welcome_screen', to: 'homepage#welcome_screen'

  get 'message_window', to: 'messages#message_window'
  get 'user_book_chat', to: 'messages#user_book_chat'
  get 'host_book_chat', to: 'messages#host_book_chat'

  post 'host_book_send_message', to: 'messages#host_book_send_message'
  post 'user_book_send_message', to: 'messages#user_book_send_message'

  get 'mark_as_important', to: 'messages#mark_as_important'
  get 'unmark_as_important', to: 'messages#unmark_as_important'

  # get 'dynamic_messages', to: 'messages#dynamic_messages'
  # post 'dynamic_messages', to: 'messages#dynamic_messages'

  get 'forget_password_form', to: 'password_resets#new'

  # get 'password_reset_form', to: 'password_resets#edit'

  # post 'update_password', to: 'password_resets#update'

  get 'edit_profile', to: 'dashboard#edit_profile_page'
  post 'update_profile', to: 'dashboard#update_profile'

  get 'new_book', to: 'book#new'
  get 'book_detail_page', to: 'book#book_details'
  get 'see_all_books', to: 'book#see_all_books'
  get 'request_book_details', to: 'book#request_book_details'
  post 'send_request_book_message', to: 'book#send_request_book_message'
  get 'see_all_external_books', to: 'book#see_all_external_books'
  get 'delete_book', to: 'book#delete_book'

  post 'add_book', to: 'book#add_book'
  get 'edit_book', to: 'book#edit_book_page'
  post 'update_book', to: 'book#update_book'
  get 'review', to: 'book#review'

  # get 'new_book_ad', to: 'book_ads#new'
  # post 'add_book_ad', to: 'book_ads#add_book_ad'

  post 'submit_feedback', to: 'feedback#submit_feedback'
  post 'submit_category', to: 'category#submit_category'

  resources :sessions, only: [:create]
  resources :users
  resources :password_resets
  resources :dashboard
  resources :password_resets
  resources :books
  # resources :books do
  #   collection do 
  #     get :autocomplete
  #   end
  # end
  # resources :book_ads
  resources :feedback
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  # before_action :get_user,         only: [:edit, :update]
  # # before_action :valid_user,       only: [:edit, :update]
  # before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
  	user = User.find_by(email: params[:password_reset][:email])
  	if user
  		user.send_password_reset_email
  		redirect_to login_path, :notice => "Email sent with password reset instructions."
  	else
  		flash[:error] = "Email address not found or blank"
      redirect_to forget_password_form_path
  	end
	end

	# def edit
	#   @user = User.find(params[:id])
	# end

	# def update
	#   @user = User.find_by_password_reset_token!(params[:password_reset_token])
 #    if params[:user][:password].empty?               # Case (3)
 #      flash[:error] = "Password can't be empty."
 #      redirect_to password_reset_form_url(@user.password_reset_token,id: @user.id,email: @user.email)
 #    elsif @user.password_reset_token.blank? && @user.password_reset_sent_at.present?
 #      flash[:error] = "Password reset link has been used previously."
 #      redirect_to login_path
	#   elsif @user.update_attributes(user_params)
	#   	@user.update(password_reset_token: '')
	#     redirect_to login_path, :notice => "Password has been reset!"
	#   else
	#     render :edit
	#   end
	# end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired."
    elsif @user.update_attributes(user_params)
      redirect_to login_path, :notice => "Password has been reset!"
    else
      render :edit
    end
  end

	# def update
 #    # byebug
 #    @user = User.find_by(email: params[:email])
 #    if params[:user][:password].empty?               # Case (3)
 #      flash[:error] = "Password can't be empty."
 #      redirect_to password_reset_form_url(@user.password_reset_token,id: @user.id,email: @user.email)
 #    elsif @user.password_reset_token.blank?                 # Case (3)
 #      flash[:error] = "Password reset link has been used previously."
 #      redirect_to login_path
 #    elsif @user.update_attributes(user_params)          # Case (4)
 #      @user.update(password_reset_token: '')
 #      flash[:success] = "Password has been reset."
 #      redirect_to login_path
 #    else
 #      flash[:error] = "Error Occured during Reset."
 #      redirect_to login_path                                   # Case (2)
 #    end
 #  end

  private

    def user_params
      params.require(:user).permit(User.attribute_names)
    end

    # Before filters

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # Confirms a valid user.
    # def valid_user
    #   unless (@user &&
    #           @user.authenticated?(:reset, params[:id]))
    #     redirect_to root_url
    #   end
    # end

    # Checks expiration of reset token.
    # def check_expiration
    #   if @user.password_reset_expired?
    #     flash[:error] = "Password reset has expired."
    #     redirect_to new_password_reset_url
    #   end
    # end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<%- if flash[:error] %>
  <div class='alert alert-danger'><%= flash[:error] %></div>
<% end %>
<% if flash[:success] %>
  <div class='alert alert-success'><%= flash[:success] %></div>
<% end %>
<div class="password-reset-form">
    <%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
    <h2 class="text-center">Reset password</h2>   
    <%= hidden_field_tag :email, @user.email %>    
<!--     <div class="form-group">
        <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
    </div> -->
    <div class="form-group">
        <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
    </div>
    <div class="form-group">
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password Confirmation' %>
    </div>
    <div class="form-group">
        <%= f.submit 'Update password', class: 'btn btn-primary btn-block' %>
    </div>       
  <% end %>
</div><br><br><br><br><br><br>

app/views/password_resets/new.html.erb
<%- if flash[:error] %>
  <div class='alert alert-danger'><%= flash[:error] %></div>
<% end %>
<% if flash[:success] %>
  <div class='alert alert-success'><%= flash[:success] %></div>
<% end %>
<div class="forget-password-form">
  <%= form_for(:password_reset, url: password_resets_path) do |f| %>
    <h3 class="text-center">Forget password</h3>   
    <!-- <p>Please enter your email address and we will send you a link to reset your password.</p> -->
    <div class="form-group">
        <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
    </div>
    <div class="form-group">
        <%= f.submit 'Submit', class: 'btn btn-primary btn-block' %>
    </div>  
  <% end %>
  <div class= "text-center">
    Already a member? <%= link_to 'Log in', login_path,class: 'link-color' %>
  </div>
  <div class= "text-center">
    New User? <%= link_to 'Click here to create an account.', sign_up_path,class: 'link-color' %>
  </div>
</div><br><br><br><br><br><br><br><br>