config/routes.rb
Rails.application.routes.draw do
  # get 'book_ads/new'
  # get 'books/new'
  root 'homepage#welcome_screen'

  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'sign_up', to: 'users#new'

  get 'confirm_email', to: 'users#confirm_email'
  get 'confirmation_page', to: 'users#confirmation_page'
  # get 'welcome_screen', to: 'homepage#welcome_screen'
  get 'user_dashboard', to: 'dashboard#user_dashboard'
  
  get 'message_window_new', to: 'dashboard#message_window_new'
  # post 'advanced_search_link', to: 'dashboard#advanced_search_link'
  post 'advanced_search_results', to: 'dashboard#advanced_search_results'
  get 'advanced_search_results', to: 'dashboard#advanced_search_results'
  get 'unread_message_count', to: 'dashboard#unread_message_count'
  # get 'edit_profile', to: 'dashboard#edit_profile_page'
  # post 'update_profile', to: 'dashboard#update_profile'

  get 'mark_it_read_host', to: 'messages#mark_it_read_host'
  get 'mark_it_read_user', to: 'messages#mark_it_read_user'

  get 'welcome_screen', to: 'homepage#welcome_screen'

  get 'message_window', to: 'messages#message_window'
  get 'user_book_chat', to: 'messages#user_book_chat'
  get 'host_book_chat', to: 'messages#host_book_chat'

  post 'host_book_send_message', to: 'messages#host_book_send_message'
  post 'user_book_send_message', to: 'messages#user_book_send_message'

  get 'mark_as_important', to: 'messages#mark_as_important'
  get 'unmark_as_important', to: 'messages#unmark_as_important'

  # get 'dynamic_messages', to: 'messages#dynamic_messages'
  # post 'dynamic_messages', to: 'messages#dynamic_messages'

  get 'forget_password_form', to: 'password_resets#new'

  # get 'password_reset_form', to: 'password_resets#edit'

  # post 'update_password', to: 'password_resets#update'

  get 'edit_profile', to: 'dashboard#edit_profile_page'
  post 'update_profile', to: 'dashboard#update_profile'

  get 'new_book', to: 'book#new'
  get 'book_detail_page', to: 'book#book_details'
  get 'see_all_books', to: 'book#see_all_books'
  get 'request_book_details', to: 'book#request_book_details'
  post 'send_request_book_message', to: 'book#send_request_book_message'
  get 'see_all_external_books', to: 'book#see_all_external_books'
  get 'delete_book', to: 'book#delete_book'

  post 'add_book', to: 'book#add_book'
  get 'edit_book', to: 'book#edit_book_page'
  post 'update_book', to: 'book#update_book'
  get 'review', to: 'book#review'

  # get 'new_book_ad', to: 'book_ads#new'
  # post 'add_book_ad', to: 'book_ads#add_book_ad'

  post 'submit_feedback', to: 'feedback#submit_feedback'
  post 'submit_category', to: 'category#submit_category'

  resources :sessions, only: [:create]
  resources :users
  resources :password_resets
  resources :dashboard
  resources :password_resets
  resources :books
  # resources :books do
  #   collection do 
  #     get :autocomplete
  #   end
  # end
  # resources :book_ads
  resources :feedback
end

app/models/book.rb
class Book < ActiveRecord::Base
	# searchkick
  belongs_to :user
  belongs_to :category
  has_many :book_images
  has_many :book_messages
  has_many :book_requests
  validates_presence_of :author,:book_name,:description,:category_id,:country_field,:state_field,:city_field,:price,:availability_status
  scope :active, -> { where(book_status: ["Active"]) }
  scope :available, -> { where availability_status: "Available" }

	def get_default_image_for_show_page
		if !self.book_images.blank?
			self.book_images.first.image.url(:thumb)	
		else
			return ActionController::Base.helpers.asset_path("default-slideshow-image.jpg")
		end
	end

	def get_default_image_for_index_page
		if !self.book_images.blank?
			self.book_images.first.image.url(:thumb)	
		else
			return ActionController::Base.helpers.asset_path("default-slideshow-image.jpg")
		end
	end

	def book_requested_before
		# byebug
		@book_requests = BookRequest.where(book_id: self.id).count > 0 ? true : false
		return @book_requests
	end

	def location_formating
		self.country_field + '(' + self.state_field + ',' + self.city_field + ')'
	end


	def self.advance_search(session_user_id,book_name,category,city,top_search,bottom_search)

		@my_books = Book.where.not(user_id: session_user_id).active.available.pluck(:id)
		search = book_name.present? ? book_name : nil
		if top_search
			# byebug
			if search
				@book_ids = Book.where("book_name LIKE ?", "%#{search}%").where.not(user_id: session_user_id).active.available.pluck(:id)
			else
				@book_ids = @my_books
			end
		elsif bottom_search
			# byebug
			if search && category.present? && city.blank?
				@category = Category.where("name LIKE ?", "%#{category}%").pluck(:id)
				@book_ids = Book.where("book_name LIKE ?", "%#{search}%").where(category_id: @category).where.not(user_id: session_user_id).active.available.pluck(:id)
			elsif search && category.blank? && city.blank?
				@book_ids = Book.where("book_name LIKE ?", "%#{search}%").where.not(user_id: session_user_id).active.available.pluck(:id)
			elsif search.blank? && category.present? && city.blank?	
				@category = Category.where("name LIKE ?", "%#{category}%").pluck(:id)
				@book_ids = Book.where(category_id: @category).where.not(user_id: session_user_id).active.available.pluck(:id)
			elsif search.present? && category.blank? && city.present?	
				@book_ids = Book.where("book_name LIKE ? AND city_field LIKE ?", "%#{search}%","%#{city}%").where.not(user_id: session_user_id).active.available.pluck(:id)
			elsif search.blank? && category.present? && city.present?	
				@category = Category.where("name LIKE ?", "%#{category}%").pluck(:id)
				@book_ids = Book.where("city_field LIKE ?","%#{city}%").where(category_id: @category).where.not(user_id: session_user_id).active.available.pluck(:id)
			elsif search.blank? && category.blank? && city.present?	
				@book_ids = Book.where("city_field LIKE ?","%#{city}%").where.not(user_id: session_user_id).active.available.pluck(:id)
			elsif search.present? && category.present? && city.present?	
				@category = Category.where("name LIKE ?", "%#{category}%").pluck(:id)
				@book_ids = Book.where("book_name LIKE ? AND city_field LIKE ?", "%#{search}%","%#{city}%").where(category_id: @category).where.not(user_id: session_user_id).active.available.pluck(:id)
			elsif search.blank? && category.blank?	&& city.blank?
				@book_ids = @my_books
			else
				@book_ids = []
			end
		end
		return @book_ids
	end


end

app/controllers/book_controller.rb
class BookController < ApplicationController
	layout "user_dashboard_layout"

	def new
		@book = Book.new
		@user = User.find(session[:user_id])
		@categories = Category.all
		if @user.check_profile_complete_status(session[:user_id])
		else
			flash[:error] = "You are not authorised to Add Book since your profile is Incomplete,So complete it fast."
      redirect_to edit_profile_path
    end
	end

	def add_book
		# byebug
		@user = User.find(session[:user_id])
		@book = Book.new(book_params)
		@book.book_status = "Active"
		@book.user_id = @user.id
		if @user.check_profile_complete_status(session[:user_id])
			if @book.save
				if params[:book_images]
	        params[:book_images].each { |book_image|
	          @book.book_images.create(image: book_image)
	        }
	 			end
					flash[:success] = "Book Added Successfully"
	    		redirect_to new_book_path
	    	else
	    		flash.now[:error] = "Error while Adding Book.."
	      	render action: 'new'
	    	end
	    else
	    	flash[:error] = "You are not authorised to Add Book since your profile is Incomplete,So complete it fast."
	      render action: 'new'
	    end
	end

	def edit_book_page
		@book = Book.find(params[:format])
		@categories = Category.all
	end

	def update_book
		@book = Book.find(params[:book_id])
		if @book.update_attributes(book_params)
			if params[:book_images]
        params[:book_images].each { |book_image|
          @book.book_images.create(image: book_image)
        }
 			end
			flash[:success] = "The Book was updated successfully."
			redirect_to :action => 'edit_book_page' , :format=> params[:book_id]
  	else
  		flash[:error] = "Error while updating Book."
			redirect_to :action => 'edit_book_page' , :format=> params[:book_id]
  	end	
	end

	# def autocomplete
 #    render json: book.search(params[:query], {
 #      fields: ["book_name"],
 #      match: :word_start,
 #      limit: 10,
 #      load: false,
 #      misspellings: {below: 5}
 #    }).map(&:book_name)
 #  end

	def book_details
		@book = Book.find(params[:format])
	end

	def see_all_books
		@books = Book.active.all.paginate(:page => params[:page], :per_page => 10)
	end

	def see_all_external_books
		# @external_books = book.where.not(user_id: session[:user_id]).active.available.paginate(:page => params[:page], :per_page => 10)
		@external_books = Book.includes(:category,:user).where.not(user_id: session[:user_id]).active.available.paginate(:page => params[:page], :per_page => 10)
	end

	def request_book_details
		@book = Book.find(params[:format])
		@particular_user_books = Book.active.available.where(user_id: @book.user_id)
	end

	def send_request_book_message
		# byebug
		puts params[:book_id]
		@book_request = BookRequest.new
		@book_request.book_id = params[:book_id]
		@book_request.user_id = session[:user_id]
		@book_request.status = "Open"
		if @book_request.save
			# byebug
			@book_message = BookMessage.new(message_description: params[:message_description],book_request_id: @book_request.id,sender: "user",sender_id: session[:user_id],receipient_id: @book_request.book.user_id,host_is_read: false,user_is_read: true)
			if params[:message_description].present?
				@book_message.save
				flash[:success] = "Book Requested Successfully"
    		redirect_to user_dashboard_path
    	else
    		flash[:error] = "Message can't be Blank"
    		redirect_to :action => 'request_book_details' , :format=> params[:book_id]
    	end
		end
	end

	def delete_book
		@book = Book.find(params[:format])
		@book.update(book_status: "Inactive")
		flash[:success] = "The Book was deleted successfully."
		redirect_to user_dashboard_path
	end


	def book_params
		params.require(:book).permit(Book.attribute_names)
	end
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/book/book_details.html.erb
 

	<div style="display: none;">
		<% @book.book_images.each do |book_image| %>
	  	<a style="cursor: pointer;" href="<%= book_image.image.url(:original) %>" data-fancybox="images-preview" 
	     data-width="280" data-height="420"
	     data-thumb="<%= book_image.image.url(:thumb) %>"></a>
	  <%end%>
	</div>

  <div class="container">
  	<div class="form-group">
    	<h4 class="pseudo_border">Book Details</h4>
    </div>
    <table class="table" style="">
      <tbody>
        <tr>
          <td>
              <a class="d-block mb-4 h-100" style="cursor: pointer;" href="<%= @book.get_default_image_for_show_page %>"
						     data-fancybox="images-preview"
						     data-thumbs='{"autoStart":true}'>
						    <img src="<%= @book.get_default_image_for_show_page %>" width="280" height="420" />
							</a>
          </td>
          <td style="width:68%;">
          		<p class="display-label" style="float: right;"><i class="fas fa-rupee-sign"></i> <%= @book.price %></p>
              <p><%= @book.book_name %> By,<%= @book.author %><br><%= "(" << @book.category.try(:name) << ")"  %></p>
              <!-- <hr></hr> -->
              <div style="float: right;"><label class="heading-label">Book Availability</label> <p class="display-label"><%= @book.availability_status %></p></div>
              <div class="form-group">
				      	<label class="heading-label">Book Owner</label>
				      	<p class="display-label"><%= @book.user.name  %></p>
    					</div>
              <!-- <hr></hr> -->
              <div class="form-group">
				      	<label class="heading-label">Location</label>
				      	<p class="display-label"><%= @book.location_formating %></p>
    					</div>
              <label class="heading-label">Description</label>
  						<!-- <div id="parent"> -->
				    		<p class="display-label" id="description_link">
			    				<%= @book.description %>
			    			</p>
			    			<!-- <a class="collapsed" data-toggle="collapse" href="#description_link" aria-expanded="false" aria-controls="description_link"></a> -->
  						<!-- </div><br> -->
  						<div class="form-group">
    						<a href="<%= edit_book_path(@book.id) %>" class="btn btn btn-secondary"><i class="fas fa-edit"></i> Edit Details</a>
    					</div>
          </td>
        </tr>
      </tbody>
    </table>
	</div>

app/views/book/new.html.erb
	<br>
	<div class="container">
	    <h3 class="pseudo_border">Post New Book</h3>
	  	<hr>
	  	<%= form_for @book, :url => add_book_path, method: "post", html:{class: 'form-horizontal', role: 'form', multipart: 'true'}  do |f| %>
			<div class="row">
		      <!-- left column -->
		      
		      	<!-- edit form column -->
	    	<div class="col-md-9">
          <%if flash[:error]%>
						<div class="error_messages alert alert-danger"><%= flash[:error] %></div>
					<% end %>
					<%if flash[:success]%>
						<div class="error_messages alert alert-success"><%= flash[:success] %></div>
					<% end %>
		       		<!-- <h3>Personal info</h3> -->

			    <% if @book.errors.any? %>
			      <br>
			      <div class="error_messages alert alert-danger">
			        <ul>
			          <% for message in @book.errors.full_messages %>
			            <li><%= message %></li>
			          <% end %>
			        </ul>
			      </div>
			    <% end %>
					<form>
				  	<div class="form-row">
					    <div class="form-group col-md-6">
				      	<label>Book Name</label><font color="#F8304D">*</font>
				      	<%= f.text_field :book_name, {class: 'form-control'}  %>
					    </div>
					    <div class="form-group col-md-6">
							  <label class="control-label" for="email">
							    Category
							  </label><font color="#F8304D">*</font>
							  <div class="input-group">
							  	<%= f.select :category_id,all_category,{include_blank: " Select Category"}, {class: 'form-control'}  %>
							    <div class="input-group-addon" style="border-radius: 0px;">
							    	<a href="#" role="button" title="Click here to add new Category" data-toggle="modal" data-target="#categoryModal" data-whatever="@mdo">
							    		<i class="fas fa-plus" style="color:black;"></i>
							    	</a>
							    </div>
							  </div>
							</div>
						</div>
						<div class="form-row">
					    <div class="form-group col-md-6">
				      	<label>Author</label><font color="#F8304D">*</font>
				      	<%= f.text_field :author, {class: 'form-control'}  %>
					    </div>

					    <div class="form-group col-md-6">
				      	<label>Price(INR)</label><font color="#F8304D">*</font>
				      	<%= f.number_field :price, {class: 'form-control'}  %>
					    </div>
						</div>
						<div class="form-row">
					    <div class="form-group col-md-4">
				      	<label>Country</label><font color="#F8304D">*</font>
				      	<%= f.text_field :country_field, class: 'form-control',value:@user.country_field  %>
					    </div>
					    <div class="form-group col-md-4">
				      	<label>State</label><font color="#F8304D">*</font>
				      	<%= f.text_field :state_field, class: 'form-control',value:@user.state  %>
					    </div>
					    <div class="form-group col-md-4">
				      	<label>City</label><font color="#F8304D">*</font>
				      	<%= f.text_field :city_field, class: 'form-control',value:@user.city  %>
					    </div>
						</div>
						<div class="form-group">
    					<label>Description</label><font color="#F8304D">*</font>
    					<%= f.text_area :description, {class: 'form-control'}  %>
  					</div>
						<div class="form-row">
					    <div class="form-group col-md-6">
				      	<label>Book Availability</label><font color="#F8304D">*</font>
				      	<%= f.select :availability_status, [["Select One", ""],["Available", "Available"], ["Not Available", "Not Available"]], {}, {class: "form-control"} %>
					    </div>

					    <div class="form-group col-md-6">
				      	<label>Upload Images</label><br>
				      	<%= file_field_tag "book_images[]", type: :file, multiple: true,accept: "image/x-png,image/gif,image/jpeg" %>
					    </div>
						</div>
				  	
		        <div class="form-row">
					    <div class="form-group col-md-6">
					      	<input class="btn btn-primary" name="commit" type="submit" value="Save">
					      	 <input type="reset" class="btn btn-default" value="Reset">
					    </div>
						</div>
					</form>
		    </div>
			</div>
		<%end%>
	</div>


	<div class="modal fade" id="categoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content category-modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
            Add New Category
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span class="" aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag submit_category_path do %>
              <!-- <h3>Personal info</h3> -->

        <div class="form-row">
          <div class="form-group col-md-6">
            <label>Category</label>
            <%= text_field_tag :name, params[:name], class: 'form-control'  %>
          </div>
          <div class="form-group col-md-6">
            <label>Description</label>
            <%= text_field_tag :description, params[:description], class: 'form-control'  %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= button_tag 'Save', class: 'btn btn-primary float-left', 
            data: { disable_with: "<i class='fa fa-refresh f
      a-spin'>
            </i> Saving..."} %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
      <%end%>
    </div>
  </div>
</div>

app/views/book/request_book_details.html.erb
	<div style="display: none;">
		<% @book.book_images.each do |book_image| %>
	  	<a style="cursor: pointer;" href="<%= book_image.image.url(:original) %>" data-fancybox="images-preview" 
	     data-width="280" data-height="420"
	     data-thumb="<%= book_image.image.url(:thumb) %>"></a>
	  <%end%>
	</div>

	  <div class="container">
	  	<%if flash[:error]%>
				<div class="error_messages alert alert-danger"><%= flash[:error] %></div>
			<% end %>
			<%if flash[:success]%>
				<div class="error_messages alert alert-success"><%= flash[:success] %></div>
			<% end %>
	  	<div class="form-group">
	    	<h4 class="pseudo_border">Book Details</h4>
	    </div>
	    <table class="table" style="">
	      <tbody>
	        <tr>
	          <td>
              <a class="d-block mb-4 h-100" style="cursor: pointer;" href="<%= @book.get_default_image_for_show_page %>"
						     data-fancybox="images-preview"
						     data-thumbs='{"autoStart":true}'>
						    <img src="<%= @book.get_default_image_for_show_page %>" width="280" height="420" />
							</a>
	          </td>
	          <td style="width:68%;">
	          		<p class="display-label" style="float: right;"><i class="fas fa-rupee-sign"></i> <%= @book.price %></p>
	              <p><%= @book.book_name %> By,<%= @book.author  %><br><%= "(" << @book.category.try(:name) << ")"  %></p>
	              <!-- <hr></hr> -->
	              <div style="float: right;"><label class="heading-label">Book Availability</label> <p class="display-label"><%= @book.availability_status %></p></div>
	              <div class="form-group">
					      	<label class="heading-label">Book Owner</label>
					      	<p class="display-label"><%= @book.user.name  %></p>
	    					</div>
	              <!-- <hr></hr> -->
	              <div class="form-group">
					      	<label class="heading-label">Location</label>
					      	<p class="display-label"><%= @book.location_formating %></p>
	    					</div>
	              <label class="heading-label">Description</label>
	  						<!-- <div id="parent"> -->
					    		<p class="display-label" id="description_link">
				    				<%= @book.description %>
				    			</p>
				    			<!-- <a class="collapsed" data-toggle="collapse" href="#description_link" aria-expanded="false" aria-controls="description_link"></a> -->
	  						<!-- </div><br> -->
						    
	          </td>
	        </tr>
	      </tbody>
	    </table>
		</div>

		<div class="container">

			<div class="form-group">
	    	<h4 class="pseudo_border">About the Provider</h4>
	    	<!-- <p display-label><%= @book.availability_status %></p> -->
	    </div>

	    <div class="row">
	    	<div class="col-md-4">
	    		<a style="cursor: pointer;" hef="#" title="<%=@book.user.name%>">
	    			<%= image_tag @book.user.profile_pic.present? ? @book.user.profile_pic.url(:thumb) : "default-profile-image.png",class: 'rounded-circle profile-front-page-image' %>
	    		</a>
	    	</div>
	    	<div class="col-md-8">
	    		<p style="font-size: 16px;"><%= @book.user.name %></p>
	    		<div id="parent">
		    		<p class="collapse display-label" id="about_the_provider_link">
		    			<%= @book.user.about_yourself %>
		    		</p>
		    		<a class="collapsed" data-toggle="collapse" href="#about_the_provider_link" aria-expanded="false" aria-controls="about_the_provider_link"></a>
	    		</div>
	    	</div>
	    </div><br><br>

	    <%= form_tag send_request_book_message_path do %>
   		<%= hidden_field_tag(:book_id, @book.id ) %>
				<div class="form-group">
					<input id="x" type="hidden" name="message_description">
					<trix-editor autofocus class="trix-content" input="x" placeholder="Type your message..." data-intro="true"></trix-editor>
				</div>
				<div class="row">
          <div class="col-md-12">
             <input class="btn" name="bottom_search_button" id="send_msg_btn" type="submit" value="Send Message" style="border-radius: 0px;">
          </div>
        </div>
      <%end%>

    </div>

		<div class="container" style="padding-left: 0px;">
			<div class="row">
				<div class="col-md-11">
					<% if @particular_user_books.count > 0 %>
						<h3 class="pseudo_border" style="padding-left: 11px;">More Books Offered By,Owner: <%= @book.user.name %></h3>
					<%end%>
				</div>
				<div class="col-md-1">
					<!-- < if @particular_user_books.count >= 4 %>
						<a href="<%= see_all_external_books_path %>" style="line-height: 50px;">See All</a>
					<end%> -->
				</div>
			</div>
			<% if @particular_user_books.count <= 4 %>
				<div class="ext_books_scroller" data-slick='{"slidesToShow": <%=  @particular_user_books.count %>}'>
			<%else%>
				<div class="ext_books_scroller">
			<%end%>
				<% @particular_user_books.each do |particular_user_book| %>
					<div class="col-md-3 mb-3">
						<a href="<%= request_book_details_path(particular_user_book) %>" style="text-decoration: none;">

							<div class="flip-card">
							  <div class="flip-card-inner">
							    <div class="flip-card-front">
							      <%= image_tag particular_user_book.get_default_image_for_index_page,class: '', height: '320' ,width: '240' %>
							    </div>
							    <div class="flip-card-back">
							      <h3 title="<%= particular_user_book.book_name %>"><%= truncate(particular_user_book.book_name, length:15) %><br><%= "(" << particular_user_book.category.try(:name) << ")"  %></h3> 
							      <p><%= particular_user_book.user.name %></p> 
							      <p><%=  particular_user_book.location_formating %></p>
							      <div class="card-footer" style="top: 85px;position: relative;">
								    	<div class="row">
								    		<div class="col-md-4">
										    	<%= link_to "" do %>
													  <i class="far fa-heart" style="color: #212529;"></i>
													<% end %>
												</div>
												<div class="col-md-3">
													
												</div>
												<div class="col-md-5">
								      		<span style="color: #212529;margin-right: 2px;"><i class="fas fa-rupee-sign"></i> <%= particular_user_book.price %></span>
								      	</div>
						      		</div>
						    		</div>
							  	</div> 
					    	</div>
							</div>

						</a>
					</div>
				<%end%>
			</div>
		</div>
	</div>

app/views/book/review.html.erb
<div id="particles-js"></div>

app/views/book/see_all_books.html.erb
<div class="container">
  <div class="row mb-2">
  	<h3 class="pseudo_border" style="padding-left: 11px;">My Books</h3>
  	<% @books.each do |book| %>
	    <div class="col-md-12">
	      <div class="card flex-md-row mb-4 box-shadow h-md-250 index-page-cards">
	      	<a href="<%= book_detail_page_path(book) %>" style="text-decoration: none;">
	      	<img class="img-fluid img-thumbnail" style="height: 240px;width: 180px;margin: 15px;" src="<%= book.get_default_image_for_index_page%>" alt=""></a>
	        <div class="card-body d-flex flex-column align-items-start">
	          <h4 class="mb-0">
	          	<%= truncate(book.book_name, length: 30) %> By,<%=  %><br><%= "(" << book.category.try(:name) << ")"  %>&nbsp;&nbsp;&nbsp;<%= image_tag book.availability_status == "Not Available" ? "not-available-black-24dp.png" : '' %>
	          </h4>
	          <!-- <div class="mb-1 text-muted">< book.user.name %></div> -->
	          <p>Location:<%= book.location_formating %></p>
	          <p><%= truncate(book.description, length: 105) %></p>
	          <p class="mb-1 text-muted">by Owner: <a><%= book.user.name %></a>, <%= book.created_at %></p>
	          <p display-label><i class="fas fa-rupee-sign"></i> <%= book.price %></p>
	          <a href="<%= edit_book_path(book) %>" class="btn btn btn-secondary edit-details-btn"><i class="fas fa-edit"></i> Edit Details</a>
	          <a href="<%= book_detail_page_path(book) %>" class="btn btn-success view-details-btn"><i class="fas fa-eye"></i> View Details</a>
	        </div>
	      </div>
	      <!-- <hr> -->
	    </div>
    <%end%>
  	</div>
	</div>
	<!--News card-->

  <br>
  <div class="digg_pagination" style="float:right;">
  	<%= will_paginate @books %>
	</div>
</div><br><br>

app/views/book/see_all_external_books.html.erb
<div class="container">
  <div class="row mb-2">
  	<h3 class="pseudo_border" style="padding-left: 11px;">Recently Uploaded Books</h3>
  	<% @external_books.each do |external_book| %>
	    <div class="col-md-12">
	      <div class="card flex-md-row mb-4 box-shadow h-md-250 index-page-cards">
	      	<a href="<%= request_book_details_path(external_book) %>" style="text-decoration: none;">
	      	<img class="img-fluid img-thumbnail" style="height: 240px;width: 180px;margin: 15px;" src="<%= external_book.get_default_image_for_index_page%>" alt=""></a>
	        <div class="card-body d-flex flex-column align-items-start">
	          <h4 class="mb-0">
	          	<%= truncate(external_book.book_name, length: 30) %> By,<%=  %><br><%= "(" << external_book.category.try(:name) << ")"  %>
	          </h4>
	          <!-- <div class="mb-1 text-muted"><= external_book.user.name %></div> -->
	          <p class="location">Location: <%= external_book.location_formating %></p>
	          <p><%= truncate(external_book.description, length:105) %></p>
	          <p class="mb-1 text-muted">by Owner: <a><%= external_book.user.name %></a>, <%= external_book.created_at %></p>
      			<p display-label><i class="fas fa-rupee-sign"></i> <%= external_book.price %></p>
	          <a href="<%= request_book_details_path(external_book) %>" class="btn btn-success view-details-btn"><i class="fas fa-eye"></i> View Details</a>
	        </div>
	      </div>
	      <!-- <hr> -->
	    </div>
    <%end%>
  </div>
</div><br>
<div class="digg_pagination" style="float:right;">
	<%= will_paginate @external_books %>
</div>
<br><br>