config/routes.rb
Rails.application.routes.draw do
  # get 'book_ads/new'
  # get 'books/new'
  root 'homepage#welcome_screen'

  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'sign_up', to: 'users#new'

  get 'confirm_email', to: 'users#confirm_email'
  get 'confirmation_page', to: 'users#confirmation_page'
  # get 'welcome_screen', to: 'homepage#welcome_screen'
  get 'user_dashboard', to: 'dashboard#user_dashboard'
  
  get 'message_window_new', to: 'dashboard#message_window_new'
  # post 'advanced_search_link', to: 'dashboard#advanced_search_link'
  post 'advanced_search_results', to: 'dashboard#advanced_search_results'
  get 'advanced_search_results', to: 'dashboard#advanced_search_results'
  get 'unread_message_count', to: 'dashboard#unread_message_count'
  # get 'edit_profile', to: 'dashboard#edit_profile_page'
  # post 'update_profile', to: 'dashboard#update_profile'

  get 'mark_it_read_host', to: 'messages#mark_it_read_host'
  get 'mark_it_read_user', to: 'messages#mark_it_read_user'

  get 'welcome_screen', to: 'homepage#welcome_screen'

  get 'message_window', to: 'messages#message_window'
  get 'user_book_chat', to: 'messages#user_book_chat'
  get 'host_book_chat', to: 'messages#host_book_chat'

  post 'host_book_send_message', to: 'messages#host_book_send_message'
  post 'user_book_send_message', to: 'messages#user_book_send_message'

  get 'mark_as_important', to: 'messages#mark_as_important'
  get 'unmark_as_important', to: 'messages#unmark_as_important'

  # get 'dynamic_messages', to: 'messages#dynamic_messages'
  # post 'dynamic_messages', to: 'messages#dynamic_messages'

  get 'forget_password_form', to: 'password_resets#new'

  # get 'password_reset_form', to: 'password_resets#edit'

  # post 'update_password', to: 'password_resets#update'

  get 'edit_profile', to: 'dashboard#edit_profile_page'
  post 'update_profile', to: 'dashboard#update_profile'

  get 'new_book', to: 'book#new'
  get 'book_detail_page', to: 'book#book_details'
  get 'see_all_books', to: 'book#see_all_books'
  get 'request_book_details', to: 'book#request_book_details'
  post 'send_request_book_message', to: 'book#send_request_book_message'
  get 'see_all_external_books', to: 'book#see_all_external_books'
  get 'delete_book', to: 'book#delete_book'

  post 'add_book', to: 'book#add_book'
  get 'edit_book', to: 'book#edit_book_page'
  post 'update_book', to: 'book#update_book'
  get 'review', to: 'book#review'

  # get 'new_book_ad', to: 'book_ads#new'
  # post 'add_book_ad', to: 'book_ads#add_book_ad'

  post 'submit_feedback', to: 'feedback#submit_feedback'
  post 'submit_category', to: 'category#submit_category'

  resources :sessions, only: [:create]
  resources :users
  resources :password_resets
  resources :dashboard
  resources :password_resets
  resources :books
  # resources :books do
  #   collection do 
  #     get :autocomplete
  #   end
  # end
  # resources :book_ads
  resources :feedback
end

app/views/layouts/_nav_login_signup.html.erb
  <header>
    <div id="particles-js"></div>
          <!--Navbar-->
    <nav class="navbar fixed-top navbar-expand-lg navbar-expand-lg navbar-dark bg-dark scrolling-navbar" style="z-index: 3;padding: .7rem 1rem;background: #3E2723 !important;height: 70px;">
      <!-- <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light"> -->
      <!-- <nav class="navbar fixed-top navbar-expand-md navbar-dark fixed-top bg-dark"> -->

        <!-- Navbar brand -->
        <a class="navbar-brand top-logo" href="<%=welcome_screen_path%>">BOOK<font color="green">WORM</font></a>
        <%= image_tag "large_cutegreen-worm.png",class: 'worm-logo' %>
        <p class="logo-tagline">Book Sharing</p>
        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
          <div class="collapse navbar-collapse" id="basicExampleNav">

              <ul class="navbar-nav mr-auto">
                <li class="nav-item">

                </li>
              </ul>

              <ul class="navbar-nav mr-auto">
                <li class="nav-item">

                </li>
              </ul>

              <!-- <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <form>
                    <div class="input-prepend input-append">
                      <div class="btn-group">
                        <select class="search-selectpicker input-group-addon">
                          <option value="" disabled selected class="text-dark search-option">Search By</option>
                          <option class="text-dark search-option">Book</option>
                          <option class="text-dark search-option">Location</option>
                        </select>
                        <input type="text" class="form-control" placeholder="Search" id="inputGroup" style="width: 520px;border-width: 0px;border: 1px solid #cccccc;border-bottom-color: #b3b3b3;border-radius: 0px;">
                            <span class="input-group-btn">
                              <button class="btn btn-default search-btn" type="button"><i class="fa fa-search"></i></button>
                          </span>
                      </div>
                    </div>
                  </form>
                </li>
              </ul> -->

              <ul class="navbar-nav mr-auto">
                <li class="nav-item">

                </li>
              </ul>

              <ul class="navbar-nav mr-auto">
                  <li class="nav-item">

                  </li>
              </ul>

              <ul class="navbar-nav mr-auto">
                  <li class="nav-item">

                  </li>
              </ul>

              <ul class="navbar-nav mr-auto">
                  <li class="nav-item">

                  </li>
              </ul>

              <ul class="navbar-nav mr-auto">
                  <li class="nav-item">

                  </li>
              </ul>

              <ul class="navbar-nav mr-auto">
                  <li class="nav-item">

                  </li>
              </ul>

              <ul class="navbar-nav mr-auto">
                  <li class="nav-item">

                  </li>
              </ul>

              <ul class="navbar-nav mr-auto">
                  <li class="nav-item">

                  </li>
              </ul>

              <ul class="navbar-nav mr-auto">
                  <li class="nav-item">

                  </li>
              </ul>


              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="<%=login_path%>"><h4>Log In</h4></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%=sign_up_path%>"><h4>Register</h4></a>
                </li>
              </ul>

              <!-- <ul class="navbar-nav mr-auto">
                  <li class="nav-item">
                    <= link_to '<button type="button" class="btn btn-outline-warning">Submit Ad</button>'.html_safe, new_Book_ad_path %>
                  </li>
              </ul> -->
<!-- 
               <ul class="navbar-nav mr-auto">
                  <li class="nav-item">

                  </li>
              </ul> -->
            <!-- Links -->

          <!--     <form class="form-inline">
                  <div class="md-form mt-0">
                      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                  </div>
              </form> -->
          </div>
        <!-- Collapsible content -->

      </nav>


  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BOOKWORM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "custom.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css' %>
    <link href="https://fonts.googleapis.com/css?family=Chela+One|Poppins|Knewave|Josefin+Sans|Lobster" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>

    <!-- Material design theme  -->

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

    
    <head>
      <% if content_for?(:head) %>
        <%= yield(:head) %>
      <% end %>
    </head>
  </head>

  
     <!-- Navigation -->
    <%a=["http://#{APP_CONFIG['hostname']}" << "/login","http://#{APP_CONFIG['hostname']}" << "/sign_up","http://#{APP_CONFIG['hostname']}" << "/logout","http://#{APP_CONFIG['hostname']}" << "/confirmation_page","https://#{APP_CONFIG['hostname']}" << "/forget_password_frm","http://#{APP_CONFIG['hostname']}" << "/users"]%>
    <% if a.include?(request.url) %>
      <body style="padding-top: 70px;">
      <%= render 'layouts/nav_login_signup' %>
    <%else%>
      <body>
    <%end%>

  <br><br><br><br><br><br>
  <div class="container">
    <%= yield %>
  </div><br><br>

    <a id="back-to-top" href="#" class="btn btn-primary btn-sm back-to-top" role="button" title="Click to return on the top page" data-toggle="tooltip" data-placement="left"><i class="fa fa-chevron-up fa-3x" aria-hidden="true"></i></a>

    <a href="#" class="btn btn-primary btn-sm feedback-icon" role="button" title="Click to Provide Application Experience Feeback" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo"><%= image_tag "baseline_feedback_white_24dp.png" %></a>

    <!-- Button trigger modal -->

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content feedback-modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">
              <%= image_tag "feedback_brown1.jpeg",class: '',width: '770',height: '200' %>   
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span class="feedback-close-button" aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= form_tag submit_feedback_path do %>
            <div class="form-group">
              <%if flash[:error]%>
                <div class="error_messages alert alert-danger"><%= flash[:error] %></div>
              <% end %>
              <%if flash[:success]%>
                <div class="error_messages alert alert-success"><%= flash[:success] %></div>
              <% end %>
            </div>
                  <!-- <h3>Personal info</h3> -->

              <div class="form-row">
                <div class="form-group col-md-6">
                  <label>Name</label><font color="#F8304D">*</font>
                  <%= text_field_tag :name, params[:name], class: 'form-control'  %>
                </div>
                <div class="form-group col-md-6">
                  <label>Email</label><font color="#F8304D">*</font>
                  <%= text_field_tag :email, params[:email], class: 'form-control'  %>
                </div>
              </div>
              <div class="form-group">
                <label>Suggestion</label><font color="#F8304D">*</font>
                <%= text_area_tag :suggestion, params[:suggestion], class: 'form-control',:placeholder => "Write What you think need to be added more to improve the application."  %>
              </div>
          </div>
          <div class="modal-footer">
            <%= button_tag 'Send Suggestion', class: 'btn btn-primary float-left', 
                data: { disable_with: "<i class='fa fa-refresh f
          a-spin'>
                </i> Sending Suggestion..."} %>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
          <%end%>
        </div>
      </div>
    </div>

<!-- Modal -->
    
    <footer class="user-dashboard-footer">
        
<!--       <div class="search-text"> 
        <div class="container">
            <center>
             
               <div class="form">
                   <h4>SIGN UP TO OUR NEWSLETTER</h4>
                    <form id="search-form" class="form-search form-horizontal">
                        <input type="text" class="input-search" placeholder="Email Address">
                        <button type="submit" class="btn-search">SUBMIT</button>
                    </form>
                </div>
              </center>
            
            </div>         
        </div>    


          <div class="container" style="border-top:1px solid grey;">
            <center>  
                <div class="col-lg-6 col-lg-offset-3">
                      <ul class="menu">
                                 
                             <li>
                                <a href="#">Home</a>
                              </li>
                                   
                              <li>
                                 <a href="#">About</a>
                              </li>
                                   
                              <li>
                                <a href="#">Blog</a>
                              </li>
                                   
                              <li>
                                 <a href="#">Gallery</a>
                              </li>
                                   
                              <li>
                                <a href="#">Contact</a>
                             </li>
                   
                        </ul>
                </div>
            </center>
          </div> -->

          <div class="copyright">
            <div class="container">
              <div class="row">
                <div class="col-md-3">
                  
                </div>
                <div class="col-md-9">
                  <p><h6 class="footer-content">BOOK<font color="green">WORM</font> Copyright © 2018 All rights reserved</h6></p>
                </div>
              </div>

               
               
            </div>
          </div>
        
    </footer>

<!--     <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
      </div>
    </footer> -->
<!--     <a href="#" class="btn btn-primary btn-sm feedback-icon" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo"><i class="fa fa-comment fa-3x"></i></a> -->
    


  </body>
</html>

app/views/layouts/homepage_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BOOKWORM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "custom.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css' %>
    <link href="https://fonts.googleapis.com/css?family=Chela+One|Poppins|Knewave|Josefin+Sans|Lobster" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.3.5/jquery.fancybox.min.css" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.3.5/jquery.fancybox.min.js"></script>

    <!-- Material design theme  -->

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

  </head>

  <body>

	<!--Main Navigation-->
	<header>

  <body style="padding-top: 70px !important;">

	  <!--Main Navigation-->
	  <header>
	    <% if !session[:user_id].present? %>
	          <!--Navbar-->
	    <nav class="navbar fixed-top navbar-expand-lg navbar-expand-lg navbar-dark bg-dark scrolling-navbar" style="z-index: 3;padding: .7rem 1rem;background: #3E2723 !important;height: 70px;">
	    	<a class="navbar-brand top-logo" href="<%=welcome_screen_path%>">BOOK<font color="green">WORM</font></a>
        	<%= image_tag "large_cutegreen-worm.png",class: 'worm-logo' %>
        <p class="logo-tagline">Book Sharing</p>

	        <!-- Collapse button -->
	        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
	            aria-expanded="false" aria-label="Toggle navigation">
	            <span class="navbar-toggler-icon"></span>
	        </button>

	        <!-- Collapsible content -->
	          <div class="collapse navbar-collapse" id="basicExampleNav">

	              <ul class="navbar-nav mr-auto">
	                <li class="nav-item">

	                </li>
	              </ul>

	              <ul class="navbar-nav mr-auto">
	                <li class="nav-item">

	                </li>
	              </ul>

	              <ul class="navbar-nav mr-auto">
	                <li class="nav-item">

	                </li>
	              </ul>

	              <ul class="navbar-nav mr-auto">
	                  <li class="nav-item">

	                  </li>
	              </ul>

	              <ul class="navbar-nav mr-auto">
	                  <li class="nav-item">

	                  </li>
	              </ul>

	              <ul class="navbar-nav mr-auto">
	                  <li class="nav-item">

	                  </li>
	              </ul>

	              <ul class="navbar-nav mr-auto">
	                  <li class="nav-item">

	                  </li>
	              </ul>

	              <ul class="navbar-nav mr-auto">
	                  <li class="nav-item">

	                  </li>
	              </ul>

	              <ul class="navbar-nav mr-auto">
	                  <li class="nav-item">

	                  </li>
	              </ul>


	              <ul class="navbar-nav mr-auto">
	                <li class="nav-item">
	                  <a class="nav-link" href="<%=login_path%>"><h4>Log In</h4></a>
	                </li>
	                <li class="nav-item">
	                    <a class="nav-link" href="<%=sign_up_path%>"><h4>Register</h4></a>
	                </li>
	              </ul>

	          </div>
	        <!-- Collapsible content -->

	      </nav>


	  </header>
	  <!--Main Navigation-->

	    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light welcome-slider" style="height:500px;background-image: url(<%= asset_path 'book_front_page.jpg' %>) !important;">
	      <div class="col-md-12 p-lg-5 mx-auto my-5">
	        <h1 style="font-size: 70px;color:white;font-family: 'Josefin Sans', sans-serif;">Book Sharing Platform</h1>
	        <p class="lead font-weight-normal" style="font-size: 42px;color:white;font-family: 'Josefin Sans', sans-serif;">Enjoy Reading & Sharing Books.</p>
	        <!-- <a class="btn btn-outline-secondary" href="#">Coming soon</a> -->
	      </div>
	      <div class="product-device box-shadow d-none d-md-block"></div>
	      <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
	    </div>

	    <div class="container">
	      <%= yield %>
	    </div>

	    <a id="back-to-top" href="#" class="btn btn-primary btn-sm back-to-top" role="button" title="Click to return on the top page" data-toggle="tooltip" data-placement="left"><i class="fa fa-chevron-up fa-3x" aria-hidden="true"></i></a>

	    <a href="#" class="btn btn-primary btn-sm feedback-icon" role="button" title="Click to Provide Application Experience Feeback" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo"><%= image_tag "baseline_feedback_white_24dp.png" %></a>

	    <!-- Button trigger modal -->

	    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	      <div class="modal-dialog" role="document">
	        <div class="modal-content feedback-modal-content">
	          <div class="modal-header">
	            <h5 class="modal-title" id="exampleModalLabel">
	              <%= image_tag "feedback_brown1.jpeg",class: '',width: '770',height: '200' %>   
	            </h5>
	            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	              <span aria-hidden="true" class="feedback-close-button">&times;</span>
	            </button>
	          </div>
	          <div class="modal-body">
	            <%= form_tag submit_feedback_path do %>
	            <div class="form-group">
	              <%if flash[:error]%>
	                <div class="error_messages alert alert-danger"><%= flash[:error] %></div>
	              <% end %>
	              <%if flash[:success]%>
	                <div class="error_messages alert alert-success"><%= flash[:success] %></div>
	              <% end %>
	            </div>
	                  <!-- <h3>Personal info</h3> -->

	              <div class="form-row">
	                <div class="form-group col-md-6">
	                  <label>Name</label><font color="#F8304D">*</font>
	                  <%= text_field_tag :name, params[:name], class: 'form-control'  %>
	                </div>
	                <div class="form-group col-md-6">
	                  <label>Email</label><font color="#F8304D">*</font>
	                  <%= text_field_tag :email, params[:email], class: 'form-control'  %>
	                </div>
	              </div>
	              <div class="form-group">
	                <label>Suggestion</label><font color="#F8304D">*</font>
	                <%= text_area_tag :suggestion, params[:suggestion], class: 'form-control',:placeholder => "Write What you think need to be added more to improve the application."  %>
	              </div>
	          </div>
	          <div class="modal-footer">
	            <%= button_tag 'Send Suggestion', class: 'btn btn-primary float-left', 
	                data: { disable_with: "<i class='fa fa-refresh f
	          a-spin'>
	                </i> Sending Suggestion..."} %>
	            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	          </div>
	          <%end%>
	        </div>
	      </div>
	    </div>



	<!-- Modal -->
	    
	    <footer class="user-dashboard-footer">
	        
<!-- 	      <div class="search-text"> 
	        <div class="container">
	            <center>
	             
	               <div class="form">
	                   <h4>SIGN UP TO OUR NEWSLETTER</h4>
	                    <form id="search-form" class="form-search form-horizontal">
	                        <input type="text" class="input-search" placeholder="Email Address">
	                        <button type="submit" class="btn-search">SUBMIT</button>
	                    </form>
	                </div>
	              </center>
	            
	            </div>         
	        </div>     


	          <div class="container" style="border-top:1px solid grey;">
	            <center>  
	                <div class="col-lg-6 col-lg-offset-3">
	                      <ul class="menu">
	                                 
	                             <li>
	                                <a href="#">Home</a>
	                              </li>
	                                   
	                              <li>
	                                 <a href="#">About</a>
	                              </li>
	                                   
	                              <li>
	                                <a href="#">Blog</a>
	                              </li>
	                                   
	                              <li>
	                                 <a href="#">Gallery</a>
	                              </li>
	                                   
	                              <li>
	                                <a href="#">Contact</a>
	                             </li>
	                   
	                        </ul>
	                </div>
	            </center>
	          </div> -->


      <div class="copyright">
	      <div class="container">
	        <div class="row">
	          <div class="col-md-3">
	            
	          </div>
	          <div class="col-md-9">
	            <p><h6 class="footer-content">BOOK<font color="green">WORM</font> Copyright © 2018 All rights reserved</h6></p>
	          </div>
	        </div>
	         
	      </div>
	    </div>
	        
	    </footer>

	    

	  </body>
  <%end%>
</html>

app/views/layouts/iframe.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BOOKWORM</title>
  <%= stylesheet_link_tag "custom.css" %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css' %>   
  <%= csrf_meta_tags %>
</head>
<body>

	<%= yield %>

</body>
</html>